# Generated by Django 3.2.4 on 2021-09-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_buyer_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buyer/'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='provider/'),
        ),
    ]
