# Generated by Django 3.2.4 on 2021-09-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210902_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
