# Generated by Django 3.2.4 on 2021-09-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_auto_20210908_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aff_id', models.CharField(max_length=20)),
                ('total_sales', models.IntegerField(max_length=55)),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.buyer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
