# Generated by Django 3.2.4 on 2021-09-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='total_sales',
            field=models.IntegerField(),
        ),
    ]
